name: build-and-test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: docker build -t control-node-serial .
    - name: Build and test
      run: |
        docker run --rm                             \
          -v $(pwd):/shared                         \
          control-node-serial                       \
          make realclean coverage
